FROM quay.io/ansible/awx-ee:latest

USER root

# Install kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

# Install kubernetes Python client + Ansible collection
RUN pip3 install kubernetes && \
    ansible-galaxy collection install kubernetes.core

USER 1000
